version: '3.8'
services:
  quizzes_db:
    image: postgres
    restart: always
    container_name: vugo_quiz_db
    environment:
      - POSTGRES_USER=db_user
      - POSTGRES_PASSWORD=db_pass
      - POSTGRES_DB=quizzes
    ports:
      - '5432:5432'
  users_db:
      image: postgres
      restart: always
      container_name: vugo_users_db
      environment:
        - POSTGRES_USER=db_user
        - POSTGRES_PASSWORD=db_pass
        - POSTGRES_DB=users
      ports:
        - '5431:5432'